---
title: "Quelques mots à propos du blog et de moi même"
date: 2020-06-08T00:56:06+02:00
draft: true
---

== Hello 

image:https://avatars0.githubusercontent.com/u/12487815?s=400&u=e32f81f48448d35b637b383ea2612cbb09351756&v=4[Avatar]

I am a french developper, living in France too. I'm currently working in the medical industry as C++ Software Engineer, 
and more recently working on CI/CD, and server administration trying to instaurate the DevOps culture in my company.

I'm really passionate about computer science and all the domains that cross it. Like CyberSecurity, Server administration,
software developement, a bit of hardware and IOTs (but I'm really bad at it.).

== Why this blog ? 

I wanted to make a blog, to help people self hosting services. And for non tech people it is sometime helpful to have some kind of tutorial
 or article rather than a "tech" documentation to start with.

It just happen suddenly after helping some folks on Reddit (r/selfhosted and r/homelab). I know there is a lot of people that are already 
writing great articles but wanted to join the adventure too. (And I want a traefik ambassador shirt lol.)
So I'd dcided to use Hugo, which seemed a nice static content tool, it is still in alpha (or beta) I think, and is a bit harsh to tame, especially
when it comes to create a special theme for your blog. (*By the way the current theme, used here is not mine and is called smol)
Anyway, hugo works fine, for some micro blogging in Markdown.

The source code of the blog is located at https://github.com/NokiDev/blog with all the posts, and everything.
I'd like even if you're a non tech user, to create a github account (or gitlab account when I would have mirrored the repository.) 
And try to participate.
You can file "issues" in which you can ask for help, share some question with the community, maybe get help from it.  
You can create a pull request, to submit a correction about an article, and even a translation if you like.

== What this blog is about

A huge part of this blog will be about my homelab, as the name tell a collection of machine that are running on my home network.
About how I achieve to set up it, which problems I encountered, which services I'm running, how I monitor them ? 
*Spoiler, they're not really monitored. Sorry I know it's hard to hear. BUT it will be the occasion to make some posts about it later :)*.

Another part of this blog may be about software development, C++, Go, Js maybe. But I'm not really sure yet.

And finally I think it would be great to had some posts company's stories ( if they authorize me to). Which may be about issues we encountered and how did we solve them.
